version: "3.3"
services:
  db:
    image: postgres
    restart: "no"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vask-net

volumes:
  pgdata:

networks:
  vask-net:
